services:
  easyearth-service:
    image: maverickmiaow/easyearth:local
    container_name: easyearth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3781:3781"
    volumes:
      - .:/usr/src/app # Sync the application code
      - ${BASE_DIR:-./data}:/usr/src/app/easyearth_base # base directory
      - ${MODEL_DIR:-./.cache/easyearth/models}:/usr/src/app/.cache/models # model directory
    environment:
      - PYTHONUNBUFFERED=1
      - BASE_DIR=/usr/src/app/easyearth_base
      - MODEL_CACHE_DIR=/usr/src/app/.cache/models
