name: easyearth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - setuptools>=21.0.0
  - gunicorn=22.0.0
  - flask-marshmallow
  - marshmallow-sqlalchemy
  - flask-cors
  - connexion
  - numpy=2.0.2
  - rasterio=1.4.3
  - pillow=11.1.0
  - geopandas=1.0.1
  - transformers=4.49.0
  - pytorch=2.6.0
  - huggingface_hub=0.29.3
  - pytest
  - ipdb
  - pyyaml>=5.1
  - matplotlib
  - pip
  - ultralytics
  - segment-geospatial
  - groundingdino-py
  - pip:
      - connexion[swagger-ui]
      - connexion[flask]
      - connexion[uvicorn]
      - flask-testing