version: '3.8'   # More recent features

services:
  easyearth-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3781:3781"
    volumes:
      - .:/usr/src/app
      - /home/yan/Downloads:/usr/src/app/data
    environment:
      - PYTHONUNBUFFERED=1

    # tty: true
    # stdin_open: true
