version: '3.8'   # More recent features

services:
  easyearth-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3781:3781"
    volumes:
      - .:/usr/src/app
      - ./user:/usr/src/app/user
#      - /home/yan/Downloads:/usr/src/app/data
#      - type: bind
#      # TODO: verify and update. For now if the data path changes, the docker image needs to be rebuilt to update the path..and make the alternative folder more flexible or more general that fits most users and os.
#        source: ${DATA_DIR:-/home/yan/Downloads/data}
#        target: /usr/src/app/user
#    environment:
#      - PYTHONUNBUFFERED=1
#      - EASYEARTH_DATA_DIR=${DATA_DIR:-/home/yan/Downloads/data}

    # tty: true
    # stdin_open: true
