name: Build and Deploy Docker Image

on:
    push:
        branches:
        - main
        paths-ignore:
        - 'README.md'
        - '.github/**'
        - '.gitignore'
        - 'easyearth_plugin/**'
        paths:
        - 'Dockerfile'
#        - 'docker-compose.yml'
        - 'environment.yml'
        - 'requirements.txt'
        - 'easyearth/**'
    pull_request:
        branches:
        - main
        paths-ignore:
        - 'README.md'
        - '.github/**'
        - '.gitignore'
        - 'easyearth_plugin/**'
        paths:
        - 'Dockerfile'
#        - 'docker-compose.yml'
        - 'environment.yml'
        - 'requirements.txt'
        - 'easyearth/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image with test tag
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/easyearth:test .

    - name: Run tests in Docker container
      run: |
        docker run --rm ${{ secrets.DOCKER_USERNAME }}/easyearth:test pytest --maxfail=1 --disable-warnings -q

    - name: Tag as lastest after tests pass
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/easyearth:test ${{ secrets.DOCKER_USERNAME }}/easyearth:latest

    - name: Push both test and latest images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/easyearth:test
        docker push ${{ secrets.DOCKER_USERNAME }}/easyearth:latest