name: Build and Deploy Docker Image

on:
     push:
         branches:
         - yan
         - lucia
         paths:
         - 'Dockerfile'
 #        - 'docker-compose.yml'
         - 'environment.yml'
         - 'requirements.txt'
         - 'easyearth/**'
    pull_request:
        branches:
        - master
        paths:
        - 'Dockerfile'
#        - 'docker-compose.yml'
        - 'environment.yml'
        - 'requirements.txt'
        - 'easyearth/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image with a branch tag
      if: github.ref_name == 'yan'
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/easyearth:${{ github.ref_name }} .

    # Tag and push as 'latest' only on master
    - name: Tag image as latest
      if: github.ref_name == 'master'
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/easyearth:master ${{ secrets.DOCKER_USERNAME }}/easyearth:latest

    # Push branch-tagged image (including master for traceability, optional)
    - name: Push branch-tagged image
      if: github.ref_name == 'yan'
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/easyearth:${{ github.ref_name }}

    - name: Push image as latest
      if: github.ref_name == 'master'
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/easyearth:latest