name: Docker Image
# This workflow builds a Docker image for EasyEarth App and pushes it to Docker Hub.

on:
     push:
         branches:
         - yan
#         - lucia
         paths:
         - 'Dockerfile'
 #        - 'docker-compose.yml'
         - 'environment.yml'
         - 'requirements.txt'
         - 'easyearth/**'
#         - '.github/workflows/deploy.yml'
     pull_request:
        branches:
        - master
        paths:
        - 'Dockerfile'
#        - 'docker-compose.yml'
        - 'environment.yml'
        - 'requirements.txt'
        - 'easyearth/**'
#        - '.github/workflows/deploy.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image with test tag
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/easyearth:test .

#    - name: Run server and tests in Docker container
#      run: |
#        docker run --rm -p 3781:3781 ${{ secrets.DOCKER_USERNAME }}/easyearth:test sh -c "
#          python -m easyearth.app --host 0.0.0.0 --port 3781 &
#          sleep 10
#          python3 easyearth/tests/test_sam_server.py
#        "

    - name: Tag as lastest after tests pass
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/easyearth:test ${{ secrets.DOCKER_USERNAME }}/easyearth:latest

    - name: Push latest image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/easyearth:latest