name: Upload Linux Env
# This GitHub Actions workflow uploads a Linux environment for the EasyEarth app to a GitHub release.

on:
  push:
    branches:
      - deactivate
    paths:
      - requirements.txt
#      - .github/workflows/upload_linux_env.yml
#  pull_request:
#    branches:
#      - master
#    paths:
#      - requirements.txt

jobs:
  upload-env:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12' # Specify the Python version you need

      - name: Create virtual environment & install dependencies
        run: |
          python -m venv --copies easyearth_env
          source easyearth_env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Back to repo root
        run: cd ${{ github.workspace }}

      - name: Start EasyEarth app & run alive test
        working-directory: ${{ github.workspace }}
        run: |
          source easyearth_env/bin/activate
          python -m easyearth.app --host 0.0.0.0 --port 3781 &
          sleep 10  # Wait for the app to start
          python -m unittest easyearth.tests.test_alive_controller

      - name: zip the environment
        run: |
            tar -czf easyearth_env_linux.tar.gz easyearth_env

      - name: Check if release with tag exists
        id: get_release
        uses: octokit/request-action@v2.4.0
        with:
          route: GET /repos/${{ github.repository }}/releases/tags/linux-env-v1
        continue-on-error: true   # so workflow continues if not found

      - name: Delete release if found
        if: ${{ steps.get_release.outcome == 'success' }}
        uses: octokit/request-action@v2.4.0
        with:
          route: DELETE /repos/${{ github.repository }}/releases/tags/linux-env-v1

      - name: Delete existing tag (if exists)
        run: |
          git tag -d linux-env-v1 || true
          git push origin :refs/tags/linux-env-v1 || true

      - name: Create or Update GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: linux-env-v1
          release_name: EasyEarth Linux Env
          body: |
            This release contains the Linux environment for EasyEarth.
            Use it to set up the app on a Linux machine.
            This is a pre-release for testing purposes.
          draft: false
          prerelease: true

      - name: Upload zipped environment to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./easyearth_env_linux.tar.gz
          asset_name: easyearth_env_linux.tar.gz
          asset_content_type: application/gzip
